# -*- mode: python ; coding: utf-8 -*-
import os
from pathlib import Path

# Get current directory
current_dir = Path(os.getcwd())

a = Analysis(
    ['api_server.py'],
    pathex=[str(current_dir)],
    binaries=[],
    datas=[
        (str(current_dir / 'core'), 'core'),
        (str(current_dir / 'parsers'), 'parsers'), 
        (str(current_dir / 'utils'), 'utils'),
    ],
    hiddenimports=[
        'uvicorn.lifespan.on',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.main',
        'uvicorn.server',
        'fastapi',
        'fastapi.applications',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.responses',
        'pydantic',
        'pydantic.main',
        'pydantic.fields',
        'core.database',
        'core.search_manager',
        'core.indexer',
        'parsers.pdf_parser',
        'parsers.docx_parser',
        'parsers.xlsx_parser',
        'parsers.text_parser',
        'parsers.doc_parser',
        'parsers.xls_parser',
        'parsers.base_parser',
        'utils.file_utils',
        'utils.fuzzy_search',
        'utils.chinese_tokenizer',
        'openai',
        'psutil',
        'jieba',
        'multiprocessing',
        'multiprocessing.pool',
        'sqlite3',
        'asyncio',
        'json',
        'argparse',
        'pathlib',
        'tempfile',
        'shutil',
        'signal',
        'socket',
        'time',
        'sys',
        'os',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='filesearch-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)